# Generated by Django 4.2 on 2026-03-11 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Подарок (тип)', 'verbose_name_plural': 'Подарки (типы)'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.RemoveField(
            model_name='item',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Условная стоимость'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('child', 'Ребенок'), ('helper', 'Помощник Деда Мороза'), ('courier', 'Курьер'), ('warehouse', 'Складская служба'), ('charity', 'Благотворительная организация'), ('admin', 'Администратор')], default='child', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст письма')),
                ('scan', models.ImageField(blank=True, null=True, upload_to='letters/', verbose_name='Скан-копия')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено'), ('processing', 'В обработке'), ('completed', 'Выполнено')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters', to=settings.AUTH_USER_MODEL, verbose_name='Ребенок')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_letters', to=settings.AUTH_USER_MODEL, verbose_name='Проверено помощником')),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('reserved', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='mainapp.item')),
            ],
            options={
                'verbose_name': 'Складской запас',
                'verbose_name_plural': 'Складские запасы',
            },
        ),
        migrations.CreateModel(
            name='GiftOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает сборки'), ('packing', 'Комплектуется'), ('ready', 'Готов к отправке'), ('shipped', 'Передан курьеру'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(related_name='orders', to='mainapp.item', verbose_name='Подарки в заказе')),
                ('letter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='mainapp.letter', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'Заказ подарков',
                'verbose_name_plural': 'Заказы подарков',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Назначен курьер'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('failed', 'Не удалось доставить')], default='assigned', max_length=20, verbose_name='Статус доставки')),
                ('route_data', models.JSONField(blank=True, null=True, verbose_name='Данные маршрута (JSON)')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Курьер')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='mainapp.giftorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
