# Generated by Django 4.2 on 2026-03-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_item_options_remove_item_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='scan',
        ),
    ]
